-- Expand brand_products with all columns from the master price list spreadsheet.
-- The existing `cost` column maps to Unit Cost; `srp` and `retail_upc` already exist.

ALTER TABLE brand_products
  ADD COLUMN IF NOT EXISTS item_rank          text,
  ADD COLUMN IF NOT EXISTS kehe_item          text,
  ADD COLUMN IF NOT EXISTS unfi_east_item     text,
  ADD COLUMN IF NOT EXISTS unfi_west_item     text,
  ADD COLUMN IF NOT EXISTS kehe_upc_old       text,
  ADD COLUMN IF NOT EXISTS inner_pack_gtin    text,
  ADD COLUMN IF NOT EXISTS case_pack_gtin     text,
  ADD COLUMN IF NOT EXISTS single_bottle_upc  text,
  ADD COLUMN IF NOT EXISTS uom                text,
  ADD COLUMN IF NOT EXISTS unit_pack          text,
  ADD COLUMN IF NOT EXISTS inner_pack         text,
  ADD COLUMN IF NOT EXISTS master_case_pack   text,
  ADD COLUMN IF NOT EXISTS unit_length        numeric,
  ADD COLUMN IF NOT EXISTS unit_width         numeric,
  ADD COLUMN IF NOT EXISTS unit_height        numeric,
  ADD COLUMN IF NOT EXISTS inner_length       numeric,
  ADD COLUMN IF NOT EXISTS inner_width        numeric,
  ADD COLUMN IF NOT EXISTS inner_height       numeric,
  ADD COLUMN IF NOT EXISTS case_length        numeric,
  ADD COLUMN IF NOT EXISTS case_width         numeric,
  ADD COLUMN IF NOT EXISTS case_height        numeric,
  ADD COLUMN IF NOT EXISTS case_cube          numeric,
  ADD COLUMN IF NOT EXISTS mc_gross_weight    numeric,
  ADD COLUMN IF NOT EXISTS ti                 numeric,
  ADD COLUMN IF NOT EXISTS hi                 numeric,
  ADD COLUMN IF NOT EXISTS case_cost          numeric,
  ADD COLUMN IF NOT EXISTS delivery_method    text,
  ADD COLUMN IF NOT EXISTS shelf_life_production numeric,
  ADD COLUMN IF NOT EXISTS shelf_life_retailer   numeric,
  ADD COLUMN IF NOT EXISTS moq                text,
  ADD COLUMN IF NOT EXISTS cert_non_gmo       boolean,
  ADD COLUMN IF NOT EXISTS cert_organic       boolean,
  ADD COLUMN IF NOT EXISTS cert_gluten_free   boolean,
  ADD COLUMN IF NOT EXISTS cert_kosher        boolean,
  ADD COLUMN IF NOT EXISTS cert_vegan         boolean,
  ADD COLUMN IF NOT EXISTS cert_other         text,
  ADD COLUMN IF NOT EXISTS cost_change_date   text,
  ADD COLUMN IF NOT EXISTS old_cost           numeric;
